name: funcog
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy
  - scipy
  - numba
  - numexpr
  - joblib
  - tqdm
  - pandas
  - matplotlib
  - python-dotenv
  - pip
  - pip:
      - brainconn
